export const testList = [
	{
		type:3,
		process: 100,
		id: 'dfa',
		tag: '设计工作',
		src: '../../../static/image/film.png',
		name: '准备本周哈哈哈',
		time: '12:00 PM,10月2日',
		color: '#23cc52',
		list: ['工作汇报', '技能分享', '哈哈哈'],
		locate: '家',
	},
	{	
		type:3,
		process: 100,
		id: 'dfa',
		tag: '设计工作',
		// src: '../../../static/image/film.png',
		name: '准备本周哈哈哈',
		time: '12:00 PM,10月2日',
		color: '#23cc52',
		list: ['工作汇报', '技能分享', '哈哈哈'],
		locate: '家',
	},
	{	
		type:3,
		process: 100,
		id: 'dfa',
		tag: '设计工作',
		src: '../../../static/image/film.png',
		name: '准备本周哈哈哈',
		time: '12:00 PM,10月2日',
		color: '#23cc52',
		list: ['工作汇报', '技能分享', '哈哈哈'],
		locate: '家',
	},
	{
		type:3,
		process: 100,
		id: 'dfa',
		tag: '设计工作',
		src: '../../../static/image/film.png',
		name: '准备本周哈哈哈',
		time: '12:00 PM,10月2日',
		color: '#23cc52',
		// list: ['工作汇报', '技能分享', '哈哈哈'],
		locate: '家',
	},
	
];

export const scrollerList = [
	{	
		type:1,
		process: 100,
		id: 'dfa',
		tag: '设计工作',
		src: '../../../static/image/film.png',
		name: '准备本周哈哈哈',
		time: '12:00 PM,10月2日',
		color: '#23cc52',
		list: ['工作汇报', '技能分享', '哈哈哈'],
		locate: '家',

	},
	{
			type:1,
		process: 100,
		id: 'dfa',
		tag: '设计工作',
		// src: '../../../static/image/film.png',
		name: '准备本周哈哈哈',
		time: '12:00 PM,10月2日',
		color: '#23cc52',
		list: ['工作汇报', '技能分享', '哈哈哈'],
		locate: '家',

	},
	{
			type:1,
		process: 100,
		id: 'dfa',
		tag: '设计工作',
		src: '../../../static/image/film.png',
		name: '准备本周哈哈哈',
		time: '12:00 PM,10月2日',
		color: '#23cc52',
		list: ['工作汇报', '技能分享', '哈哈哈'],
		locate: '家',

	},
	{
			type:1,
		process: 100,
		id: 'dfa',
		tag: '设计工作',
		src: '../../../static/image/film.png',
		name: '准备本周哈哈哈',
		time: '12:00 PM,10月2日',
		color: '#23cc52',
		// list: ['工作汇报', '技能分享', '哈哈哈'],
		locate: '家',

	},
	
];
